/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KYqZ4YQFn8x
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"


export function Component() {
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-950">
      <header className="bg-white dark:bg-gray-900 shadow">
        <div className="container mx-auto px-4 md:px-6 py-4 flex items-center justify-between">
          <Link className="flex items-center gap-2 font-bold text-xl" href="#">
            <ClubIcon className="w-6 h-6" />
            Sports Bash
          </Link>
          <div className="flex items-center gap-4">
            <Link
              className="hidden md:inline-flex items-center gap-2 text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              <PackageIcon className="w-5 h-5" />
              Products
            </Link>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800 dark:border-gray-800"
                  size="icon"
                  variant="ghost"
                >
                  <img
                    alt="Avatar"
                    className="rounded-full"
                    height="32"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "32/32",
                      objectFit: "cover",
                    }}
                    width="32"
                  />
                  <span className="sr-only">Toggle user menu</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Orders</DropdownMenuItem>
                <DropdownMenuItem>Wishlist</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuItem>Support</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
            <Button className="flex items-center gap-2" size="sm" variant="outline">
              <ShoppingCartIcon className="w-4 h-4" />
              Cart
            </Button>
          </div>
        </div>
      </header>
      <main className="container mx-auto px-4 md:px-6 py-12">
        <section className="grid md:grid-cols-2 gap-12">
          <div className="grid gap-6">
            <div>
              <h1 className="text-3xl font-bold tracking-tight">Welcome to Sports Bash</h1>
              <p className="text-gray-500 dark:text-gray-400">
                Find the perfect sports gear for your active lifestyle.
              </p>
              <div className="mt-4">
                <h2 className="text-2xl font-bold">About Us</h2>
                <p className="text-gray-500 dark:text-gray-400">
                  Sports Bash is a leading retailer of high-quality sports equipment and apparel. We are dedicated to
                  providing our customers with the best products and services to support their active lifestyles.
                </p>
              </div>
              <div className="mt-4">
                <h2 className="text-2xl font-bold">Measure Feet Size</h2>
                <Link className="text-gray-500 dark:text-gray-400 hover:underline" href="#">
                  Follow our simple guide to find your ideal size.
                </Link>
              </div>
              <div className="mt-4">
                <h2 className="text-2xl font-bold">Measure Body Size</h2>
                <Link className="text-gray-500 dark:text-gray-400 hover:underline" href="#">
                  Get the perfect fit every time.
                </Link>
              </div>
            </div>
            <div className="grid gap-4">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-6 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                href="#"
              >
                Shop Products
              </Link>
            </div>
          </div>
          <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View Products</span>
            </Link>
            <img
              alt="Sports Gear"
              className="object-cover w-full h-full"
              height={400}
              src="https://imgs.search.brave.com/Yj-KOqzOhpRYnQqNKGL0mK2HQuETKw34S9PJ53GDIIc/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9sb3Zl/bGxjZG4uYi1jZG4u/bmV0L3Byb2R1Y3Rz/LzE5ODEwODcuanBn"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-gray-900/80 to-transparent" />
            <div className="absolute bottom-0 left-0 p-6 text-white">
              <h2 className="text-2xl font-bold">Sports Gear</h2>
              <p className="text-sm">Explore our collection of high-quality sports equipment.</p>
            </div>
          </div>
        </section>
        <section className="mt-12">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold">Featured Products</h2>
          </div>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 1"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Basketball Shoes</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">High-performance basketball shoes</p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$79.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 2"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Running Shorts</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">Lightweight and breathable running shorts</p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$39.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 3"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Yoga Mat</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">Premium yoga mat for your practice</p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$59.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 4"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Resistance Bands</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">
                  Set of resistance bands for strength training
                </p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$24.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="mt-12">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl font-bold">All Products</h2>
          </div>
          <div className="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 1"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Basketball Shoes</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">High-performance basketball shoes</p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$79.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 2"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Running Shorts</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">Lightweight and breathable running shorts</p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$39.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 3"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Yoga Mat</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">Premium yoga mat for your practice</p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$59.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 4"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Resistance Bands</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">
                  Set of resistance bands for strength training
                </p>
                <div className="flex items-center justify-between mt-2">
                  <p className="font-semibold">$24.99</p>
                  <Button size="sm" variant="outline">
                    <ShoppingCartIcon className="w-4 h-4 mr-2" />
                    Add to Cart
                  </Button>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <Link className="absolute inset-0 z-10" href="#">
                <span className="sr-only">View Product</span>
              </Link>
              <img
                alt="Product 1"
                className="object-cover w-full aspect-square"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="p-4">
                <h3 className="font-semibold text-lg">Basketball Shoes</h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm">High-performance basketball shoes</p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function ClubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.28 9.05a5.5 5.5 0 1 0-10.56 0A5.5 5.5 0 1 0 12 17.66a5.5 5.5 0 1 0 5.28-8.6Z" />
      <path d="M12 17.66L12 22" />
    </svg>
  )
}


function PackageIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function ShoppingCartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}
